"""Generates every Dr VPN logo asset from one definition.

Run from the repo root:  pip install pillow resvg-py && python branding/generate.py
Outputs: adaptive-icon vectors, legacy launcher PNGs, in-app logo, store icon,
Android TV banner and the status-bar icon.
"""
import io
import os

import resvg_py
from PIL import Image, ImageDraw, ImageFont

RES = 'android/app/src/main/res/'
SHIELD = ("M54 27C61.5 31.5 69 33.5 77 33.5L77 52C77 67 67.5 77.5 54 83"
          "C40.5 77.5 31 67 31 52L31 33.5C39 33.5 46.5 31.5 54 27Z")
FACET = "M54 27C61.5 31.5 69 33.5 77 33.5L77 52C77 67 67.5 77.5 54 83Z"
CROSS = ("M51 42.5H57A1.5 1.5 0 0 1 58.5 44V50.5H65A1.5 1.5 0 0 1 66.5 52V58"
         "A1.5 1.5 0 0 1 65 59.5H58.5V66A1.5 1.5 0 0 1 57 67.5H51A1.5 1.5 0 0 1 49.5 66"
         "V59.5H43A1.5 1.5 0 0 1 41.5 58V52A1.5 1.5 0 0 1 43 50.5H49.5V44"
         "A1.5 1.5 0 0 1 51 42.5Z")
BG1, BG2 = '#3D9BFF', '#0040C1'
CR1, CR2 = '#2E8CFF', '#0047C7'
FACET_COLOR = '#DCE8FF'


def logo_svg(background=True):
    bg = '<rect width="108" height="108" fill="url(#bg)"/>' if background else ''
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 108 108"><defs>
<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG1}"/><stop offset="1" stop-color="{BG2}"/></linearGradient>
<linearGradient id="cr" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{CR1}"/><stop offset="1" stop-color="{CR2}"/></linearGradient></defs>
{bg}<g transform="translate(54 55) scale(0.9) translate(-54 -55)">
<path d="{SHIELD}" fill="#FFFFFF"/><path d="{FACET}" fill="{FACET_COLOR}"/><path d="{CROSS}" fill="url(#cr)"/></g></svg>'''


def render(svg, w, h=None):
    data = resvg_py.svg_to_bytes(svg_string=svg, width=w, height=h or w)
    return Image.open(io.BytesIO(bytes(data))).convert('RGBA')


def write(path, text):
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def gradient(x1, y1, x2, y2, c1, c2):
    return (f'<aapt:attr name="android:fillColor"><gradient android:type="linear" '
            f'android:startX="{x1}" android:startY="{y1}" android:endX="{x2}" android:endY="{y2}" '
            f'android:startColor="#FF{c1[1:]}" android:endColor="#FF{c2[1:]}" /></aapt:attr>')


VECTOR_HEAD = '''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
'''
GROUP = 'android:pivotX="54" android:pivotY="55" android:scaleX="0.9" android:scaleY="0.9"'


def vectors():
    write(RES + 'drawable/ic_logo_background.xml', VECTOR_HEAD + f'''    <!-- Dr VPN brand gradient. Generated by branding/generate.py -->
    <path android:pathData="M0,0h108v108h-108z">
        {gradient(0, 0, 108, 108, BG1, BG2)}
    </path>
</vector>
''')
    write(RES + 'drawable/ic_logo_foreground.xml', VECTOR_HEAD + f'''    <!-- Dr VPN mark: two-tone shield with a medical cross. Generated by branding/generate.py -->
    <group {GROUP}>
        <path android:fillColor="#FFFFFFFF" android:pathData="{SHIELD}" />
        <path android:fillColor="#FF{FACET_COLOR[1:]}" android:pathData="{FACET}" />
        <path android:pathData="{CROSS}">
            {gradient(41.5, 42.5, 66.5, 67.5, CR1, CR2)}
        </path>
    </group>
</vector>
''')
    write(RES + 'drawable/ic_logo_monochrome.xml', VECTOR_HEAD + f'''    <!-- Themed-icon layer: shield silhouette with the cross cut out. Generated by branding/generate.py -->
    <group {GROUP}>
        <path android:fillColor="#FFFFFFFF" android:fillType="evenOdd" android:pathData="{SHIELD} {CROSS}" />
    </group>
</vector>
''')
    for name in ['ic_launcher', 'ic_launcher_round']:
        write(RES + f'mipmap-anydpi-v26/{name}.xml', '''<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_logo_background" />
    <foreground android:drawable="@drawable/ic_logo_foreground" />
    <monochrome android:drawable="@drawable/ic_logo_monochrome" />
</adaptive-icon>
''')


def launcher(px, round_=False):
    """Full icon as a launcher shows it: the inner 72/108 of the canvas, masked."""
    big = render(logo_svg(), int(px * 1.5)).crop((px // 4, px // 4, px // 4 + px, px // 4 + px))
    mask = Image.new('L', (px * 4, px * 4), 0)
    d = ImageDraw.Draw(mask)
    if round_:
        d.ellipse([0, 0, px * 4 - 1, px * 4 - 1], fill=255)
    else:
        d.rounded_rectangle([0, 0, px * 4 - 1, px * 4 - 1], radius=int(px * 4 * 0.22), fill=255)
    mask = mask.resize((px, px), Image.LANCZOS)
    out = Image.new('RGBA', (px, px), (0, 0, 0, 0))
    out.paste(big, (0, 0), mask)
    return out


def banner(w, h):
    s = w / 320
    bg = f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}"><defs>
<linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{BG1}"/><stop offset="1" stop-color="{BG2}"/></linearGradient></defs>
<rect width="{w}" height="{h}" fill="url(#g)"/></svg>'''
    img = render(bg, w, h)
    mark = render(logo_svg(False), int(180 * s)).crop((int(35 * s), int(35 * s), int(145 * s), int(145 * s)))
    x0 = int(22 * s)
    img.paste(mark, (x0, (h - mark.size[1]) // 2), mark)
    font = ImageFont.truetype('C:/Windows/Fonts/segoeuib.ttf', int(46 * s))
    ImageDraw.Draw(img).text((x0 + mark.size[0] - int(8 * s), h / 2), 'Dr VPN', font=font, fill='white', anchor='lm')
    return img


def status_icon():
    write(RES + 'drawable/ic_stat_name.xml', '''<?xml version="1.0" encoding="utf-8"?>
<!-- Dr VPN status icon: shield with a medical cross cut out (monochrome, for status bar / tile / widget). -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:fillType="evenOdd"
        android:pathData="M12,2C14.7,3.6 17.3,4.3 20.2,4.3L20.2,10.9C20.2,16.3 16.8,20 12,22C7.2,20 3.8,16.3 3.8,10.9L3.8,4.3C6.7,4.3 9.3,3.6 12,2Z M10.9,7.4H13.1Q13.6,7.4 13.6,7.9V10.2H15.9Q16.4,10.2 16.4,10.7V12.9Q16.4,13.4 15.9,13.4H13.6V15.7Q13.6,16.2 13.1,16.2H10.9Q10.4,16.2 10.4,15.7V13.4H8.1Q7.6,13.4 7.6,12.9V10.7Q7.6,10.2 8.1,10.2H10.4V7.9Q10.4,7.4 10.9,7.4Z" />
</vector>
''')


def remove(path):
    if os.path.exists(path):
        os.remove(path)


def main():
    write('branding/logo.svg', logo_svg())
    write('branding/logo-foreground.svg', logo_svg(False))
    vectors()
    for density, px in {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}.items():
        launcher(px).save(RES + f'mipmap-{density}/ic_launcher.png')
        launcher(px, True).save(RES + f'mipmap-{density}/ic_launcher_round.png')
        remove(RES + f'mipmap-{density}/ic_launcher_foreground.png')
    launcher(512).save(RES + 'drawable-nodpi/drvpn_logo.png')
    launcher(512).save('fastlane/metadata/android/en-US/images/icon.png')
    launcher(1024).save('branding/logo-1024.png')
    banner(320, 180).save(RES + 'mipmap-xhdpi/ic_banner.png')
    banner(640, 360).save('branding/banner-640x360.png')
    remove(RES + 'mipmap-xhdpi/ic_banner_foreground.png')
    remove(RES + 'mipmap-anydpi-v26/ic_banner.xml')
    remove(RES + 'values/ic_banner_background.xml')
    status_icon()
    print('ok')


if __name__ == '__main__':
    main()
