"""Builds the world map used by the server picker from Natural Earth (public domain) 1:110m data.

Usage:  python branding/world_map.py <ne_110m_land.geojson> <ne_110m_admin_0_countries.geojson>
Writes: res/drawable-nodpi/world_map.png (white land mask, tinted in the app) and
        ui/main/WorldMapPositions.kt (country code -> position on that image).
"""
import io
import json
import sys

from PIL import Image, ImageDraw

LON0, LON1 = -180.0, 180.0
LAT_TOP, LAT_BOTTOM = 84.0, -57.0  # no Antarctica
W = 1440
H = int(W * (LAT_TOP - LAT_BOTTOM) / (LON1 - LON0))
SS = 2  # supersampling

RES = 'android/app/src/main/res/'
KT = 'android/app/src/main/java/net/drvpn/app/ui/main/WorldMapPositions.kt'

# Small countries missing from the 1:110m set (lon, lat).
EXTRA = {
    'SG': (103.82, 1.35), 'HK': (114.17, 22.32), 'LU': (6.13, 49.61), 'BH': (50.55, 26.07),
    'MT': (14.45, 35.90), 'MO': (113.54, 22.19), 'AD': (1.52, 42.51), 'MC': (7.42, 43.74),
    'LI': (9.55, 47.16), 'SM': (12.46, 43.94), 'MV': (73.51, 4.17), 'MU': (57.55, -20.35),
    'BB': (-59.54, 13.19), 'SC': (55.45, -4.68), 'KN': (-62.78, 17.34), 'GD': (-61.68, 12.12),
}


def xy(lon, lat):
    return ((lon - LON0) / (LON1 - LON0) * W * SS, (LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM) * H * SS)


def polygons(geometry):
    if geometry['type'] == 'Polygon':
        yield geometry['coordinates']
    elif geometry['type'] == 'MultiPolygon':
        yield from geometry['coordinates']


def main(land_path, countries_path):
    land = json.load(io.open(land_path, encoding='utf-8'))
    img = Image.new('L', (W * SS, H * SS), 0)
    draw = ImageDraw.Draw(img)
    for feature in land['features']:
        for rings in polygons(feature['geometry']):
            draw.polygon([xy(lon, lat) for lon, lat in rings[0]], fill=255)
            for hole in rings[1:]:
                draw.polygon([xy(lon, lat) for lon, lat in hole], fill=0)
    mask = img.resize((W, H), Image.LANCZOS)
    out = Image.new('RGBA', (W, H), (255, 255, 255, 0))
    out.putalpha(mask)
    out.save(RES + 'drawable-nodpi/world_map.png', optimize=True)

    countries = json.load(io.open(countries_path, encoding='utf-8'))
    positions = {}
    for feature in countries['features']:
        p = feature['properties']
        code = p.get('ISO_A2') if p.get('ISO_A2') not in (None, '-99') else p.get('ISO_A2_EH')
        if not code or code == '-99':
            continue
        positions[code] = (p['LABEL_X'], p['LABEL_Y'])
    for code, lonlat in EXTRA.items():
        positions.setdefault(code, lonlat)

    lines = []
    for code in sorted(positions):
        lon, lat = positions[code]
        fx = (lon - LON0) / (LON1 - LON0)
        fy = (LAT_TOP - lat) / (LAT_TOP - LAT_BOTTOM)
        if 0 <= fx <= 1 and 0 <= fy <= 1:
            lines.append(f'    "{code}" to ({fx:.4f}f to {fy:.4f}f),')
    kt = '''package net.drvpn.app.ui.main

// Generated by branding/world_map.py from Natural Earth (public domain). Do not edit by hand.

/** Aspect ratio (width / height) of drawable-nodpi/world_map.png. */
internal const val WORLD_MAP_ASPECT = %sf

/** ISO country code -> position of the country's label point on world_map.png, as fractions. */
internal val WORLD_MAP_POSITIONS: Map<String, Pair<Float, Float>> = mapOf(
%s
)
''' % (f'{W / H:.4f}', '\n'.join(lines))
    with open(KT, 'w', encoding='utf-8', newline='\n') as f:
        f.write(kt)
    print('map', W, 'x', H, 'countries', len(lines))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
